### ISSUE TITLE
☂ CSV rework

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#827]
I've collected several issues regarding CSV reading / readDelim to be reworked. Most are marked with the new [CSV label](https://github.com/Kotlin/dataframe/labels/csv).
I marked them all, because most are related and solving one will require solving others and vice versa.

Let this issue be an umbrella issue linking to the relevant issues:

- [x] https://github.com/Kotlin/dataframe/issues/787
  - [x] Split readDelim and readCsv into different files, possibly a different module?
  - [x] Deprecate .read() overload, this should only exist in guess.kt https://github.com/Kotlin/dataframe/pull/902
  - [x] KDocs for each overload
  - [x] Check which CSVFormat options we can put in the readDelim and readCsv functions to create overloads without it. (Like setting the quote mark)
  - [x] Keep one overload for readDelim and readCsv with CSVFormat as option so people can set advanced settings with it.
- [x] https://github.com/Kotlin/dataframe/issues/826
- [x] https://github.com/Kotlin/dataframe/issues/508
- [x] https://github.com/Kotlin/dataframe/issues/746
- [x] https://github.com/deephaven/deephaven-csv/issues/212
- [x] https://github.com/Kotlin/dataframe/issues/687
- [x] https://github.com/Kotlin/dataframe/issues/607 Covered by https://github.com/Kotlin/dataframe/pull/935
- [x] ~https://github.com/Kotlin/dataframe/issues/593~ Covered by https://github.com/Kotlin/dataframe/pull/925
- [x] https://github.com/Kotlin/dataframe/issues/589
- [x] https://github.com/Kotlin/dataframe/issues/507
- [x] https://github.com/Kotlin/dataframe/issues/469
- [x] https://github.com/Kotlin/dataframe/issues/383
- [x] https://github.com/Kotlin/dataframe/issues/100
- [x] https://github.com/Kotlin/dataframe/issues/834
- [x] https://github.com/Kotlin/dataframe/issues/921
- [x] https://github.com/Kotlin/dataframe/issues/527
- [x] Remove opt-in
- [ ] https://github.com/Kotlin/dataframe/issues/765
- [ ] Extend CsvOption in `ImportDataSchema` annotation and Gradle Task
- [ ] Change drag-and-drop behavior in notebooks
- [ ] Documentation about new CSV implementation on the website/examples when it's no longer experimental.
- [ ] Move Compression to :core and apply to other io's

**Comment by Jolanrensen** [comment]
Not all tasks are finished. The "dataframe-csv" implementation is entering experimental stage at the 0.15.X version of DF.
The next version will stabilize it and deprecate the old implementation.

**Comment by Jolanrensen** [comment]
Related: https://github.com/Kotlin/dataframe/issues/1047

**Comment by Jolanrensen** [comment]
I'll close this for now, 99% of the relevant issues are finished
